language: python
python:
- '3.4'
- '3.5'
- '3.6'
script:
- python -m unittest discover
deploy:
  provider: pypi
  skip_existing: true
  user: janhartigan
  password:
    secure: OIvSGelMS9mM7lYUrMB4jTmxnc5OZ2pPfsBck39FOtPIbw1JXBCRKZ+P6vDWkiRMa1mXR2JxGtKHQG1WU45Qd5qJ29t3m/agYLw/HqCXV9qq/mCE1/0ex5evhuOt2U73fT9iF3I8DXsBRwUk5Sn+K59U6kb7Etk9A6vf6EWmw2sTjtX/ScuahPY+copLXn9+XKEsKqJRowHwyKQjKfjHM47RgwI51epI6nqmIFM50tgoRiVnuGHtXzEhXyymHWZG/oaHPXTc1zQ7e9+zQz9Mbh2eAniyp7OAsOAgHMiPMlqTPRU84UFl4bG0dvVNZlZ4xqFwu2RD6NvPFTM86LpRQz5C62r6GtUes6rmBTrJAoz4lEfDdNjtzEiqCIZaOZ0AQHATiiUKY9hYhkNkcx+Dl5G7d1tBh7gAexCvTDezTutS3YfsZKRe+/KrSyHzL41MO6Qj3vua1e/SGH+QPHZg25C1v/3ECoylFg0KsjxhvL3OCQLvUWgB80e3yEbd56E27EJyGbUXweocyD2SWpDDUi6VMf046OKY+EsGxdbPdITM8g3Hz2CIZoyrtWllL861QgJRHJRAhRndh8ZEFPLSUaJ0cSqqzY1G+HTaTEzXGuvhPXSNeqVXLG3700WR81vr2x/WRmz85tM8Z2pHEm36E653F/IvKUVSttTSqKmvYZ8=
  on:
    tags: true
notifications:
  email:
    on_success: never
